language: ruby
rvm:
- ruby-head
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-19mode
notifications:
  email: false
  irc:
    channels:
      - irc.oftc.net#akerl
    channel_key:
      secure: "KgYL1Re0ThDujwlm/jwmM633zEnWpQLi9njynO1nrFFKY24zFmHzFaJwWuDunYFjslCAM9PKEiFSimXUglFJCpAD5ez3FHuDZiT2xLIAsfQUPk2u7D0FtOEd1DE2h/+XleRh+m16JntJ0sfd3GCKXVNoAjI665R2P/Iv/djkL+Y="
    template:
      - '%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}'
