language: ruby
rvm:
- ruby-head
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-19mode
notifications:
  email: false
  irc:
    channels:
      - irc.oftc.net#akerl
    channel_key: sekrit
    template:
      - '%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}'
