language: ruby
rvm:
- ruby-head
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx
notifications:
  email: false
  irc:
    channels:
      - irc.oftc.net#akerl
    channel_key:
      secure: "AFEdB/WjJAI7N1LJcdBS/qtyR7hwrY0HEUp1Tq2Wyr9ieFl8VpN+GjRdncjGq+rtZe5jpE1Ind5GErHStg6UTLkocOo1ITcxLwpUhMatox6RdGLsFwTVWymV00KwRTD4S+X5cU9dfGlmGOTNuvDEjh6IarAmnQ/qb9ZX0slJHQg="
    template:
      - '%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}'
