language: ruby
rvm:
- ruby-head
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-19mode
notifications:
  email: false
  irc:
    channels:
      - irc.oftc.net#akerl
    channel_key:
      secure: "S/ilmZ3R+Y/q28T76SPcTYzaVrgdQLPbGrc2ooHI6ppE6R58eFPJufpCiJ4lUGa/+YCUYsqZ48JJgLspSZNKmLkRtBenebt+JHgmSPejAp+zYG84qhB3uwKgNNojFVlexHyuS9/5uUTGlrhtkqdJrvniO1br5teRW2ogsLxf7hY="
